# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webgroup',
            name='admins',
            field=models.ManyToManyField(related_name='group_admins', to='superbbs.UserProfile'),
        ),
        migrations.AlterField(
            model_name='webgroup',
            name='members',
            field=models.ManyToManyField(related_name='group_members', to='superbbs.UserProfile'),
        ),
    ]
