# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag_img',
            field=models.ImageField(blank=True, height_field=150, null=True, upload_to='uploads', width_field=150),
        ),
    ]
