# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbbs', '0002_article_tag_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag_img',
            field=models.ImageField(upload_to='', verbose_name='文章标题图片'),
        ),
    ]
