# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbbs', '0004_auto_20160623_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_userprofile_friends_+', to='superbbs.UserProfile'),
        ),
    ]
