# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbbs', '0005_userprofile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='_userprofile_friends_+', to='superbbs.UserProfile'),
        ),
    ]
